services:
  - type: web
    name: gwi-blog-thumbnail-creator
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: FIGMA_TOKEN
        sync: false
      - key: PEXELS_API_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: REMOVE_BG_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: "8080"
